spring.jpa.show-sql=true
spring.h2.console.enabled=true

# H2 인메모리 DB 이름을 testdb로 고정 (콘솔 접속 URL과 일치시키기 위함)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=